services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5433:5433" # Mapping the host port 5433 to the container port 5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

  web:
    container_name: backend
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile
    command: uv run gunicorn core.wsgi:application --bind 0.0.0.0:9000
    restart: always
    depends_on:
      - db
    ports:
      - "9000:9000"
