name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASS }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
        ports:
          - "5432:5432"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Create .env file
        run: |
          cat <<EOF > .env
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG=${{ secrets.DEBUG }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PASS=${{ secrets.DATABASE_PASS }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_PORT=${{ secrets.DATABASE_PORT }}
          EOF

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        env:
          DATABASE_URL: postgres://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASS }}@{{ secrets.DATABASE_HOST }}:{{ secrets.DATABASE_PORT }}/${{ secrets.DATABASE_NAME }}
        run: uv run python src/manage.py test
