name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        ports:
          - "5432:5432"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Create .env file
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        env:
          DATABASE_URL: postgres://user:password@localhost:5432/test_db
        run: uv run python src/manage.py test
